# Generated by Django 5.2.3 on 2025-06-30 04:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriProduk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, verbose_name='Nama Kategori')),
                ('deskripsi', models.TextField(blank=True, null=True, verbose_name='Deskripsi')),
            ],
            options={
                'verbose_name': 'Kategori Produk',
                'verbose_name_plural': 'Kategori Produk',
            },
        ),
        migrations.CreateModel(
            name='Pemasok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, verbose_name='Nama Pemasok')),
                ('kontak', models.CharField(max_length=100, verbose_name='Kontak')),
                ('alamat', models.TextField(verbose_name='Alamat')),
            ],
            options={
                'verbose_name': 'Pemasok',
                'verbose_name_plural': 'Pemasok',
            },
        ),
        migrations.CreateModel(
            name='Satuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50, verbose_name='Nama Satuan')),
            ],
            options={
                'verbose_name': 'Satuan',
                'verbose_name_plural': 'Satuan',
            },
        ),
        migrations.CreateModel(
            name='Pembelian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(auto_now_add=True, verbose_name='Tanggal')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total')),
                ('pemasok', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produk.pemasok', verbose_name='Pemasok')),
            ],
            options={
                'verbose_name': 'Pembelian',
                'verbose_name_plural': 'Pembelian',
            },
        ),
        migrations.CreateModel(
            name='Penjualan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(auto_now_add=True, verbose_name='Tanggal')),
                ('pelanggan', models.CharField(max_length=100, verbose_name='Nama Pelanggan')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total')),
                ('kasir', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kasir')),
            ],
            options={
                'verbose_name': 'Penjualan',
                'verbose_name_plural': 'Penjualan',
            },
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_produk', models.CharField(max_length=20, unique=True, verbose_name='Kode Produk')),
                ('nama', models.CharField(max_length=200, verbose_name='Nama Produk')),
                ('stok', models.PositiveIntegerField(default=0, verbose_name='Stok')),
                ('harga_beli', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Harga Beli')),
                ('harga_jual', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Harga Jual')),
                ('kategori', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='produk.kategoriproduk', verbose_name='Kategori')),
                ('pemasok', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='produk.pemasok', verbose_name='Pemasok')),
                ('satuan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='produk.satuan', verbose_name='Satuan')),
            ],
            options={
                'verbose_name': 'Produk',
                'verbose_name_plural': 'Produk',
            },
        ),
        migrations.CreateModel(
            name='DetailPenjualan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.PositiveIntegerField(verbose_name='Jumlah')),
                ('harga_satuan', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Harga Satuan')),
                ('penjualan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_penjualan', to='produk.penjualan', verbose_name='Penjualan')),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produk.produk', verbose_name='Produk')),
            ],
            options={
                'verbose_name': 'Detail Penjualan',
                'verbose_name_plural': 'Detail Penjualan',
            },
        ),
        migrations.CreateModel(
            name='DetailPembelian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.PositiveIntegerField(verbose_name='Jumlah')),
                ('harga_satuan', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Harga Satuan')),
                ('pembelian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_pembelian', to='produk.pembelian', verbose_name='Pembelian')),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produk.produk', verbose_name='Produk')),
            ],
            options={
                'verbose_name': 'Detail Pembelian',
                'verbose_name_plural': 'Detail Pembelian',
            },
        ),
    ]
